### ISSUE TITLE
Invalid redeclaration of synthesized implementation for protocol requirement 'allCases'

### ISSUE THREAD

**Issue by svoip** [PureSwift/Bluetooth#136]
Building the package on Xcode 12.5 I am getting such an error on line
`        public static let allCases: Set<MajorServiceClass> = [`
in 
`ClassOfDevice.swift`.

**Comment by iamWing** [comment]
Same issue here. Looks like the Swift compiler comes with Xcode 12.5 is updated

**Comment by ksinghal** [comment]
If you need this resolved ASAP, please see my pull request here: https://github.com/PureSwift/Bluetooth/pull/137
